# Gambling on the fact that Node.js is present on all environments
language: ruby

rvm:
  - 2.3.1

before_install:
  - nvm install node

install:
  - npm install
  - bundle install

before_script:
  - node --version
  - phantomjs --version
  - cd examples/dist && python -m SimpleHTTPServer 8888 &

script: npm run test
